# Generated by Django 2.2.5 on 2019-10-13 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='following',
            name='following_to',
        ),
        migrations.AddField(
            model_name='following',
            name='following_to',
            field=models.ManyToManyField(related_name='_following_following_to_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
