# Generated by Django 2.2.5 on 2019-11-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191015_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='no_of_followers',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='following',
            name='no_of_following',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
