# Generated by Django 2.2.5 on 2019-11-27 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191128_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='_follower_followed_by_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='following',
            name='following_to',
            field=models.ManyToManyField(blank=True, related_name='_following_following_to_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
