# Generated by Django 2.2.3 on 2019-08-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='profile',
            field=models.ImageField(default='images/logo.png', upload_to='images/'),
        ),
    ]
