# Generated by Django 2.2.4 on 2019-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_social_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='profile',
            new_name='posted_image',
        ),
        migrations.RemoveField(
            model_name='social',
            name='title',
        ),
    ]
