# Generated by Django 2.2.5 on 2019-12-06 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0003_auto_20190831_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='_social_liked_by_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='social',
            name='posted_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
