# Generated by Django 2.2.5 on 2019-12-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191206_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
