# Generated by Django 2.2.5 on 2019-12-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_auto_20191206_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='no_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
