# Generated by Django 2.2 on 2020-01-13 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0006_social_no_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='no_of_likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
